<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function custom_blocks_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['fun_text'] = array(
      '#markup' => '<p>Search Form Custom Text</p>',
      '#weight' => -10,
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function custom_blocks_form_search_block_form_alter(&$form, &$form_state) {
  $form['fun_text']['#markup'] = t('Search Form Custom Help Text.');
}

